### ISSUE TITLE
Not showing in settings

### ISSUE THREAD

**Issue by fraserYT** [timmmmyboy/WordPress#6]
I've followed instructions and cloned into my idnoplugins folder. I'm able to see and enable the plugin under Site Configuration/Plugins, but Wordpress doesn't appear as an option under Account Settings. I've successfully installed several other plugins using the same technique, so I think I've configured it correctly, but it's not working

**Comment by timmmmyboy** [comment]
Hmm, been a long time since I've looked at this plugin. Wondering if there were some breaking changes to the Known codebase. I'll see if I can find out.

**Comment by fraserYT** [comment]
Hey, I appreciate the reply, but if it's essentially no longer supported,
seriously don't waste any time on it. There's a very real chance that it's
me failing to configure my known install properly in the first place!

**Comment by fraserYT** [comment]
...As evidenced by the fact I just deleted and then reinstalled the plugin and it appears to be working now. Sorry to have bothered you.

**Comment by timmmmyboy** [comment]
Well I'm certainly glad to hear this thing still has some life in it! Glad to hear it's working :)
